enum ContextPreset {
  warhammer40000("""
Warhammer 40,000, often abbreviated as WH40K, is a dystopian science fiction universe set in the far distant future of the 41st millennium. This franchise, created by Games Workshop, encompasses a vast and intricate universe where humanity, under the authoritarian rule of the Imperium of Man, is on the brink of extinction. The Imperium is constantly at war with a multitude of alien races, heretical rebels, and demonic forces from the Warp, a parallel dimension of chaos and malevolence.
At the heart of the Imperium is the God-Emperor of Mankind, a psychic beacon who, despite being mortally wounded and entombed within the Golden Throne on Terra (Earth), guides humanity's starships through the Warp. The lore of WH40K is characterized by grimdark themes, where the moral ambiguity of its characters and factions plays a significant role. It's a universe where the line between good and evil is often blurred, and the cost of survival is invariably high.
The Warhammer 40,000 franchise includes tabletop games, video games, novels, and more. The novels, in particular, delve deep into the lore, exploring the lives of various characters from space marines and imperial guardsmen to the innumerable enemies of the Imperium. These narratives often highlight the grim reality of constant warfare, political intrigue, and the struggle against corruption and despair.
Notable factions within the WH40K universe include the Space Marines, genetically engineered super-soldiers who serve as the elite warriors of the Imperium; the Chaos Space Marines, former Space Marines who have turned to worship the Chaos Gods; the Eldar, an ancient and highly advanced alien race; the Orks, a war-loving and technologically primitive race; and the Tyranids, a terrifying, all-consuming swarm of alien beings.
Warhammer 40,000’s rich narrative is a dark reflection of our own world, exploring themes of power, faith, sacrifice, and the eternal conflict between light and darkness. The franchise’s extensive lore and detailed universe provide a fertile ground for storytelling, making it a beloved saga among fans of science fiction and fantasy alike.

The tone of the translation should be solemn and epic. Specifically, express it with a firm and commanding style, as in 'Forget the promise of progress and understanding.' The translation should evoke a sense of an epic or the tragedy of war, with emphasized words being conveyed powerfully. Ultimately, depict the future as bleak and inevitably consumed by war.
"""),

  warhammerFantasy("""
Warhammer Fantasy, also known simply as Warhammer, is a richly detailed high fantasy universe created by Games Workshop. Set in a fictional world reminiscent of Earth's own Middle Ages but infused with magic and populated by mythical creatures, Warhammer Fantasy unfolds across several continents, with the Old World, a dark and war-torn continent that closely mirrors Europe, serving as the primary setting for many of its stories.
This universe is characterized by its epic tales of heroism, treachery, and complex political intrigue among its diverse factions. The world of Warhammer is home to humans, dwarfs, elves (split into High, Dark, and Wood Elves), orcs and goblins, vampires, and a multitude of other fantastical beings. Each race and faction vies for power and survival in a world constantly threatened by chaos, war, and the machinations of dark gods.
Central to the lore of Warhammer Fantasy are the forces of Chaos, a malevolent power that seeks to corrupt and destroy the world. The Chaos Gods, each embodying aspects of mortal vice and horror, amass armies of followers from all races, eager to spread destruction and despair. Standing against these forces are heroes and villains alike, from noble knights and cunning wizards to tyrannical warlords and insidious assassins.
The narrative depth of Warhammer Fantasy is explored through a wide range of media, including tabletop games, novels, and video games. The novels, in particular, delve deep into the histories, cultures, and conflicts of the Warhammer world, offering readers a vast tapestry of interconnected stories and characters. From the stoic defenders of the Empire and the isolationist yet powerful High Elves to the marauding hordes of orcs and the inscrutable motives of the Skaven, a race of malevolent rat-men, each faction contributes to the rich lore and complex dynamics of the Warhammer Fantasy universe.
Warhammer Fantasy's appeal lies in its detailed world-building, where the fates of empires hinge on battles fought with sword and sorcery, and where the line between heroism and villainy is often as thin as a blade's edge. It is a world where magic and the mundane coexist, where ancient grudges and new alliances shape the destinies of countless lives. For fans of high fantasy, Warhammer offers an immersive and endlessly fascinating saga of conflict, courage, and cataclysm.""");

  final String contextDesc;
  const ContextPreset(this.contextDesc);
}
